/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segundoproyectoanalisis;

/**
 *
 * @author HP GABY
 */
public class Actividades extends javax.swing.JFrame {

    /**
     * Creates new form Actividades
     */
    public Actividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPActividades = new javax.swing.JPanel();
        jLIdActividades = new javax.swing.JLabel();
        jLDescripcionActividades = new javax.swing.JLabel();
        jLImportanciaActividades = new javax.swing.JLabel();
        jLDuracion = new javax.swing.JLabel();
        jLValorRecursoA = new javax.swing.JLabel();
        jTFIdActividades = new javax.swing.JTextField();
        jTFDuracionActividades = new javax.swing.JTextField();
        jTFValorRecursoA = new javax.swing.JTextField();
        jBAgregarActividad = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADescripcionActividades = new javax.swing.JTextArea();
        jBSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTActividadesA = new javax.swing.JTable();
        jBModificarActividad = new javax.swing.JButton();
        jCBImportanciaActiviades = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPActividades.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)), "ACTIVIDADES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Estrangelo Edessa", 0, 36))); // NOI18N

        jLIdActividades.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLIdActividades.setText("Id:");

        jLDescripcionActividades.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLDescripcionActividades.setText("Descripción:");

        jLImportanciaActividades.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLImportanciaActividades.setText("Importancia:");

        jLDuracion.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLDuracion.setText("Duración:");

        jLValorRecursoA.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLValorRecursoA.setText("Valor recurso:");

        jTFIdActividades.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N

        jTFDuracionActividades.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N

        jTFValorRecursoA.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N

        jBAgregarActividad.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jBAgregarActividad.setForeground(new java.awt.Color(0, 153, 0));
        jBAgregarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Agregar.png"))); // NOI18N
        jBAgregarActividad.setText("AGREGAR");
        jBAgregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActividadActionPerformed(evt);
            }
        });

        jTADescripcionActividades.setColumns(20);
        jTADescripcionActividades.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jTADescripcionActividades.setRows(5);
        jScrollPane2.setViewportView(jTADescripcionActividades);

        jBSalir.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jBSalir.setForeground(new java.awt.Color(0, 153, 0));
        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salida.png"))); // NOI18N
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jTActividadesA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));
        jTActividadesA.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jTActividadesA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTActividadesA);

        jBModificarActividad.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jBModificarActividad.setForeground(new java.awt.Color(0, 153, 0));
        jBModificarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Actualizar.png"))); // NOI18N
        jBModificarActividad.setText("MODIFICAR");
        jBModificarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActividadActionPerformed(evt);
            }
        });

        jCBImportanciaActiviades.setFont(new java.awt.Font("Estrangelo Edessa", 0, 14)); // NOI18N
        jCBImportanciaActiviades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR OPCION", "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout jPActividadesLayout = new javax.swing.GroupLayout(jPActividades);
        jPActividades.setLayout(jPActividadesLayout);
        jPActividadesLayout.setHorizontalGroup(
            jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPActividadesLayout.createSequentialGroup()
                .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPActividadesLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jBAgregarActividad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBModificarActividad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPActividadesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPActividadesLayout.createSequentialGroup()
                                .addComponent(jLValorRecursoA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFValorRecursoA, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPActividadesLayout.createSequentialGroup()
                                .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDescripcionActividades)
                                    .addComponent(jLIdActividades))
                                .addGap(18, 18, 18)
                                .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFIdActividades)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPActividadesLayout.createSequentialGroup()
                                .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLImportanciaActividades)
                                    .addComponent(jLDuracion))
                                .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPActividadesLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFDuracionActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPActividadesLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jCBImportanciaActiviades, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        jPActividadesLayout.setVerticalGroup(
            jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPActividadesLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPActividadesLayout.createSequentialGroup()
                        .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLIdActividades)
                            .addComponent(jTFIdActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDescripcionActividades))
                        .addGap(21, 21, 21)
                        .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLImportanciaActividades)
                            .addComponent(jCBImportanciaActiviades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDuracion)
                            .addComponent(jTFDuracionActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLValorRecursoA)
                            .addComponent(jTFValorRecursoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBAgregarActividad)
                        .addComponent(jBModificarActividad))
                    .addComponent(jBSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAgregarActividadActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBModificarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModificarActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarActividad;
    private javax.swing.JButton jBModificarActividad;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBImportanciaActiviades;
    private javax.swing.JLabel jLDescripcionActividades;
    private javax.swing.JLabel jLDuracion;
    private javax.swing.JLabel jLIdActividades;
    private javax.swing.JLabel jLImportanciaActividades;
    private javax.swing.JLabel jLValorRecursoA;
    private javax.swing.JPanel jPActividades;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADescripcionActividades;
    private javax.swing.JTable jTActividadesA;
    private javax.swing.JTextField jTFDuracionActividades;
    private javax.swing.JTextField jTFIdActividades;
    private javax.swing.JTextField jTFValorRecursoA;
    // End of variables declaration//GEN-END:variables
}
