/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author HP GABY
 */
public class Ejecutores extends javax.swing.JFrame {

    /**
     * Creates new form Ejecutores
     */
    public int tiempo;

    public Ejecutores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPEjecutores = new javax.swing.JPanel();
        jBAgregarEjecutor = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEjecutores = new javax.swing.JTable();
        jTFNombreEjecutores = new javax.swing.JTextField();
        jLNombreEjecutores = new javax.swing.JLabel();
        jLCriterioEjecutores = new javax.swing.JLabel();
        jLLimiteEjecutores = new javax.swing.JLabel();
        jCBCriterioEjecutores = new javax.swing.JComboBox<>();
        jCBLimiteEjecutores = new javax.swing.JComboBox<>();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPEjecutores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)), "EJECUTORES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Estrangelo Edessa", 0, 36))); // NOI18N

        jBAgregarEjecutor.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jBAgregarEjecutor.setForeground(new java.awt.Color(0, 153, 0));
        jBAgregarEjecutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Agregar.png"))); // NOI18N
        jBAgregarEjecutor.setText("AGREGAR");
        jBAgregarEjecutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarEjecutorActionPerformed(evt);
            }
        });

        jSalir.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jSalir.setForeground(new java.awt.Color(0, 153, 0));
        jSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salida.png"))); // NOI18N
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jTEjecutores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));
        jTEjecutores.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jTEjecutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTEjecutores);

        jTFNombreEjecutores.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N

        jLNombreEjecutores.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLNombreEjecutores.setText("Nombre:");

        jLCriterioEjecutores.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLCriterioEjecutores.setText("Criterio:");

        jLLimiteEjecutores.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLLimiteEjecutores.setText("Limite:");

        jCBCriterioEjecutores.setFont(new java.awt.Font("Estrangelo Edessa", 0, 14)); // NOI18N
        jCBCriterioEjecutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR OPCION", "TIEMPO", "RECURSOS", "IMPORTANCIA" }));

        jCBLimiteEjecutores.setFont(new java.awt.Font("Estrangelo Edessa", 0, 14)); // NOI18N
        jCBLimiteEjecutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR OPCION", "SI", "NO" }));
        jCBLimiteEjecutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBLimiteEjecutoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEjecutoresLayout = new javax.swing.GroupLayout(jPEjecutores);
        jPEjecutores.setLayout(jPEjecutoresLayout);
        jPEjecutoresLayout.setHorizontalGroup(
            jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEjecutoresLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEjecutoresLayout.createSequentialGroup()
                        .addComponent(jBAgregarEjecutor)
                        .addGap(18, 18, 18)
                        .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEjecutoresLayout.createSequentialGroup()
                        .addGroup(jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEjecutoresLayout.createSequentialGroup()
                                .addGroup(jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCriterioEjecutores)
                                    .addComponent(jLNombreEjecutores))
                                .addGap(18, 18, 18)
                                .addGroup(jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCBCriterioEjecutores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFNombreEjecutores)))
                            .addGroup(jPEjecutoresLayout.createSequentialGroup()
                                .addComponent(jLLimiteEjecutores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBLimiteEjecutores, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPEjecutoresLayout.setVerticalGroup(
            jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEjecutoresLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSalir)
                    .addComponent(jBAgregarEjecutor))
                .addGap(22, 22, 22))
            .addGroup(jPEjecutoresLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreEjecutores)
                    .addComponent(jTFNombreEjecutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCriterioEjecutores)
                    .addComponent(jCBCriterioEjecutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLLimiteEjecutores)
                    .addComponent(jCBLimiteEjecutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPEjecutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPEjecutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarEjecutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarEjecutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAgregarEjecutorActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSalirActionPerformed

    private void jCBLimiteEjecutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBLimiteEjecutoresActionPerformed
        try {
            if (jCBLimiteEjecutores.getSelectedIndex() == 1) {
                tiempo = Integer.parseInt(JOptionPane.showInputDialog(null, "ingresa una cantidad de tiempo"));
                System.err.println(tiempo);
            }
        } catch (NumberFormatException e) {
            System.err.println("[ERROR] Se debe de ingresar una cantidad ");
        }
    }//GEN-LAST:event_jCBLimiteEjecutoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejecutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejecutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejecutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejecutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejecutores().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarEjecutor;
    private javax.swing.JComboBox<String> jCBCriterioEjecutores;
    private javax.swing.JComboBox<String> jCBLimiteEjecutores;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLCriterioEjecutores;
    private javax.swing.JLabel jLLimiteEjecutores;
    private javax.swing.JLabel jLNombreEjecutores;
    private javax.swing.JPanel jPEjecutores;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTEjecutores;
    private javax.swing.JTextField jTFNombreEjecutores;
    // End of variables declaration//GEN-END:variables
}
