/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segundoproyectoanalisis;

/**
 *
 * @author HP GABY
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jPPlanificador = new javax.swing.JPanel();
        jPListaActividades = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTListaActividades = new javax.swing.JTable();
        jLOrdenarPor = new javax.swing.JLabel();
        jCBOrdenarPor = new javax.swing.JComboBox<>();
        jBCrearEjecutorPlanificador = new javax.swing.JButton();
        jBCrearActividadPlanificador = new javax.swing.JButton();
        jPListaEjecutores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTListaEjecutores = new javax.swing.JTable();
        jLTotalEjecutores = new javax.swing.JLabel();
        jLAcumulado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setFont(new java.awt.Font("Estrangelo Edessa", 0, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 153, 0));
        jLTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/sensible (2).png"))); // NOI18N
        jLTitulo.setText("EJECUTOR DE ACTIVIDADES");

        jPPlanificador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)), "PLANIFICADOR ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Estrangelo Edessa", 0, 18))); // NOI18N

        jPListaActividades.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)), "LISTA ACTIVIDADES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Estrangelo Edessa", 0, 18))); // NOI18N

        jTListaActividades.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jTListaActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTListaActividades);

        jLOrdenarPor.setFont(new java.awt.Font("Estrangelo Edessa", 0, 14)); // NOI18N
        jLOrdenarPor.setText("ORDENAR POR:");

        jCBOrdenarPor.setFont(new java.awt.Font("Estrangelo Edessa", 0, 14)); // NOI18N
        jCBOrdenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR OPCION", "TIEMPO", "RECURSOS", "IMPORTANCIA" }));

        javax.swing.GroupLayout jPListaActividadesLayout = new javax.swing.GroupLayout(jPListaActividades);
        jPListaActividades.setLayout(jPListaActividadesLayout);
        jPListaActividadesLayout.setHorizontalGroup(
            jPListaActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListaActividadesLayout.createSequentialGroup()
                .addGroup(jPListaActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPListaActividadesLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jCBOrdenarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPListaActividadesLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLOrdenarPor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPListaActividadesLayout.setVerticalGroup(
            jPListaActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListaActividadesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLOrdenarPor)
                .addGap(18, 18, 18)
                .addComponent(jCBOrdenarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListaActividadesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jBCrearEjecutorPlanificador.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jBCrearEjecutorPlanificador.setForeground(new java.awt.Color(0, 153, 0));
        jBCrearEjecutorPlanificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/CrearEjecutor.png"))); // NOI18N
        jBCrearEjecutorPlanificador.setText("CREAR EJECUTOR");

        jBCrearActividadPlanificador.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jBCrearActividadPlanificador.setForeground(new java.awt.Color(0, 153, 0));
        jBCrearActividadPlanificador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Crear.png"))); // NOI18N
        jBCrearActividadPlanificador.setText("CREAR ACTIVIDAD");

        jPListaEjecutores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)), "LISTA EJECUTORES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Estrangelo Edessa", 0, 18))); // NOI18N

        jTListaEjecutores.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jTListaEjecutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTListaEjecutores);

        jLTotalEjecutores.setFont(new java.awt.Font("Estrangelo Edessa", 0, 14)); // NOI18N
        jLTotalEjecutores.setText("TOTAL EJECUTORES");

        jLAcumulado.setFont(new java.awt.Font("Estrangelo Edessa", 0, 14)); // NOI18N
        jLAcumulado.setText("ACUMULADO");

        javax.swing.GroupLayout jPListaEjecutoresLayout = new javax.swing.GroupLayout(jPListaEjecutores);
        jPListaEjecutores.setLayout(jPListaEjecutoresLayout);
        jPListaEjecutoresLayout.setHorizontalGroup(
            jPListaEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPListaEjecutoresLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPListaEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTotalEjecutores)
                    .addComponent(jLAcumulado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPListaEjecutoresLayout.setVerticalGroup(
            jPListaEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListaEjecutoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPListaEjecutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPListaEjecutoresLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLTotalEjecutores)
                        .addGap(18, 18, 18)
                        .addComponent(jLAcumulado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPListaEjecutoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );

        javax.swing.GroupLayout jPPlanificadorLayout = new javax.swing.GroupLayout(jPPlanificador);
        jPPlanificador.setLayout(jPPlanificadorLayout);
        jPPlanificadorLayout.setHorizontalGroup(
            jPPlanificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPlanificadorLayout.createSequentialGroup()
                .addGroup(jPPlanificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPPlanificadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPListaEjecutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPlanificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPPlanificadorLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jPListaActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPPlanificadorLayout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(jBCrearEjecutorPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jBCrearActividadPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPPlanificadorLayout.setVerticalGroup(
            jPPlanificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPlanificadorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPListaActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPListaEjecutores, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPPlanificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearEjecutorPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCrearActividadPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLTitulo)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCrearActividadPlanificador;
    private javax.swing.JButton jBCrearEjecutorPlanificador;
    private javax.swing.JComboBox<String> jCBOrdenarPor;
    private javax.swing.JLabel jLAcumulado;
    private javax.swing.JLabel jLOrdenarPor;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLTotalEjecutores;
    private javax.swing.JPanel jPListaActividades;
    private javax.swing.JPanel jPListaEjecutores;
    private javax.swing.JPanel jPPlanificador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTListaActividades;
    private javax.swing.JTable jTListaEjecutores;
    // End of variables declaration//GEN-END:variables
}
